# Generated by Django 4.2.16 on 2024-09-09 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='descriptoion',
            new_name='description',
        ),
    ]
